apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-test-server
spec:
  template:
    spec:
      containers:
        - name: kube-test-server
          image: 123456789.ncr.gov-ntruss.com/kube-test-server-dev:latest