apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/client
nameSuffix: -main
images:
  - name: kube-test-client
    newName: kube-img-registry.kr.ncr.ntruss.com/kube-test-client-main
    newTag: latest
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: kube-test-client
  - path: service-patch.yaml
    target:
      kind: Service
      name: kube-test-client