# 기본 값 (base의 값들)
replicaCount: 1

image:
  repository: kube-test-server
  tag: latest

containerPort: 8080

service:
  type: NodePort
  port: 80
  annotations: {}

imagePullSecrets: ncr-secret

# 프로브 설정
readinessProbe:
  path: /health-check
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  path: /health-check
  initialDelaySeconds: 60
  periodSeconds: 15
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

# 추가 환경 변수
envFrom: []