apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-test-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-test-client
  template:
    metadata:
      labels:
        app: kube-test-client
    spec:
      containers:
        - name: kube-test-client
          image: kube-test-client:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health-check
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health-check
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
      imagePullSecrets:
        - name: ncr-secret